services:
  nginx:
    image: nginx:1.29.8-alpine3.23
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/frappe-bench.conf:ro
      - ./apps:/home/frappe/frappe-bench/apps
      - ./sites:/home/frappe/frappe-bench/sites
    depends_on:
      - web-app
    networks:
      default:
        aliases:
          - site1.local

  web-app:
    image: codingcoffee/frappe-mono:prod
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./apps:/home/frappe/frappe-bench/apps
      - ./sites:/home/frappe/frappe-bench/sites
      - ./.venv:/home/frappe/frappe-bench/env
      - ./frappe-supervisor.conf:/etc/supervisor/conf.d/frappe-bench.conf
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    env_file:
      - .frappe.env
    command: supervisord -n -c /etc/supervisor/supervisord.conf

  redis:
    image: valkey/valkey:9.0.3-alpine3.23
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mariadb:
    image: mariadb:11.8.6-noble
    env_file:
      - .mariadb.env
    volumes:
      - ./mariadb-data/mysql:/var/lib/mysql
      - ./frappe-mariadb.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
